### ISSUE TITLE
support ndt error minimization?

### ISSUE THREAD

**Issue by narutojxl** [ntnu-arl/drpm#3]
Dear authors,
Thanks for sharing this excellent work to community!
* I want to know whether drpm could be used in ndt-based error minimization pipeline lio slam system?

* BTW, the rotation convention is hamilton or JPL? I see the pose update is left multiply with old pose.
![image](https://github.com/user-attachments/assets/0b6a8989-80cc-4ed8-8b99-393cb4e8c471)
* If our rotation convention  is hamilton, is there a typo in equ 8? If rotation convention is JPL, i understand that is OK, we use local pertubation in JPL convention to calculate jacobian and to locally update (left multiply) with old pose to get new pose.
![image](https://github.com/user-attachments/assets/930c974d-f457-4cd9-bbdd-27c6824be7a9)

**Comment by johhat** [comment]
Thank you for the questions and the kind words.

1. The code can't be used as-is for NDT. It might be possible to extend the method to NDT. The key is to model spurious noise entering the Hessian. As far as I know, NDT uses covariance matrices instead of surface normals. One would need to model the spurious information induced by the covariance matrices.
2. The method can be used with either convention. Adjoint matrices can be used to relate left and right operations. The derivations in section II use left multiplications in line with ref [23]. In the implementation used for experimental evaluation, we express the Hessian and find the perturbation in the local LiDAR frame. The resulting perturbation can be used directly for right-side updates or be transformed for use in left-side updates via an appropriate adjoint transformation.
3. In (8) the negative sign stems from applying the transpose operator to the small-angle approximation of $\bar{R}_i$. $\bar{R}_i^T = Exp(\eta_i)^T \approx I + [\eta_i]_x^T = I - [\eta_i]_x$.

**Comment by narutojxl** [comment]
Thanks very much for your very kind and detailed reply, my problem is solved.
